# site settings
title: Government Shutdown
email: timekeeper@gvtshtdwn.com
description: >- # this means to ignore newlines until "baseurl:"
  The current status of the US Federal Government and 
  countdown to when the next government shutdown could occur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gvtshtdwn.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:path
image: /assets/images/gvtshtdwn-default-image.png

# build settings
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
exclude:
 - Gemfile.lock

# jekyll-seo-tag config
twitter:
  username: gvtshtdwn
  card: summary_large_image
#facebook:
  app_id: 411967176665932
  #publisher: 1234
  #admins: 1234
social:
  name: Government Shutdown
  links:
    - https://twitter.com/gvtshtdwn
#webmaster_verifications:
  #google: 1234
  #bing: 1234
  #alexa: 1234
  #yandex: 1234
  #baidu: 1234
gtm: G-61LLZHBRPT

# countdown config
funded-until: '2020/12/19'

# site defaults 
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/gvtshtdwn-default-image.png