# https://khalidabuhakmeh.com/automate-your-blog-with-github-actions
name: Twitter Promoter

on:
  push:
    branches:
      - master
  schedule:
    # 11 AM Everyday
    - cron: "00 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Blog Promoter
      uses: actions/checkout@v2
      with:
        repository: judsonlmoore/BlogPromoter

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: Run Promoter
      env: 
        twitter_account: '@gvtshtdwn'
        blog_feed_url: 'https://www.gvtshtdwn.com/feed-twitter.xml'
        twitter_access_token: ${{ secrets.twitter_access_token }}
        twitter_access_token_secret: ${{ secrets.twitter_access_token_secret }}
        twitter_consumer_key: ${{ secrets.twitter_consumer_key }}
        twitter_consumer_secret: ${{ secrets.twitter_consumer_secret }}
      run: dotnet run -c Release